[package]
name = "cksol_minter"
version = "0.1.0"
description = "Chain-key SOL minter for the Internet Computer."
authors.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true

[[bin]]
name = "cksol_minter"
path = "src/main.rs"

[features]
canbench-rs = ["dep:canbench-rs"]

[dependencies]
askama = { workspace = true }
assert_matches = { workspace = true }
bincode = { workspace = true }
canbench-rs = { workspace = true, optional = true }
candid = { workspace = true }
canlog = { workspace = true, features = ["derive"] }
cksol-types = { path = "../libs/types" }
cksol-types-internal = { path = "../libs/types-internal", features = ["event", "log"] }
derive_more = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
ic-canister-runtime = { workspace = true }
ic-cdk = { workspace = true }
ic-cdk-management-canister = { workspace = true }
ic-cdk-timers = { workspace = true }
ic-dummy-getrandom-for-wasm = { workspace = true }
ic-ed25519 = { workspace = true }
ic-http-types = { workspace = true }
ic-metrics-encoder = { workspace = true }
ic-stable-structures = { workspace = true }
icrc-cbor = { workspace = true }
icrc-ledger-types = { workspace = true }
itertools = { workspace = true }
minicbor = { workspace = true, features = ["derive"] }
num-traits = { workspace = true }
phantom_newtype = { workspace = true }
scopeguard = { workspace = true }
serde = { workspace = true }
sol_rpc_client = { workspace = true }
sol_rpc_types = { workspace = true }
solana-address = { workspace = true }
solana-hash = { workspace = true }
solana-message = { workspace = true }
solana-signature = { workspace = true }
solana-system-interface = { workspace = true, features = ["bincode"] }
solana-transaction = { workspace = true, features = ["bincode"] }
solana-transaction-status-client-types = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
async-trait = { workspace = true }
base64 = { workspace = true }
candid_parser = { workspace = true }
mockall = { workspace = true }
proptest = { workspace = true }
scraper = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true, features = ["full"] }
